// ======================================================
const COUPON_CODE_ACTIONS_TYPES = {
  POST_COUPON_CODE: "POST_COUPON_CODE",
  POST_COUPON_CODE_SUCCESS: "POST_COUPON_CODE_SUCCESS",
  POST_COUPON_CODE_FAIL: "POST_COUPON_CODE_FAIL",
};

const COUPONS_ACTIONS_TYPES = {
  GET_SELLER_COUPONS: "GET_SELLER_COUPONS",
  GET_SELLER_COUPONS_SUCCESS: "GET_SELLER_COUPONS_SUCCESS",
  GET_SELLER_COUPONS_FAIL: "GET_SELLER_COUPONS_FAIL",
};
// ======================================================
const CART_ACTIONS_TYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",
  // ===============================================
  GET_CART: "GET_CART",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAIL: "GET_CART_FAIL",
  // ===============================================
  DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
  DELETE_PRODUCT_FROM_CART_SUCCESS: "DELETE_PRODUCT_FROM_CART_SUCCESS",
  DELETE_PRODUCT_FROM_CART_FAIL: "DELETE_PRODUCT_FROM_CART_FAIL",
  // ===============================================
  PUT_CART: "PUT_CART",
  PUT_CART_SUCCESS: "PUT_CART_SUCCESS",
  PUT_CART_FAIL: "PUT_CART_FAIL",
};
// ======================================================

const WISHLIST_ACTIONS_TYPES = {
  ADD_PRODUCT_TO_WISHLIST: "ADD_PRODUCT_TO_WISHLIST",
  ADD_PRODUCT_TO_WISHLIST_SUCCESS: "ADD_PRODUCT_TO_WISHLIST_SUCCESS",
  ADD_PRODUCT_TO_WISHLIST_FAIL: "ADD_PRODUCT_TO_WISHLIST_FAIL",
  // ===============================================
  GET_WISHLIST: "GET_WISHLIST",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
  GET_WISHLIST_FAIL: "GET_WISHLIST_FAIL",
  // ===============================================
  DELETE_PRODUCT_FROM_WISHLIST: "DELETE_PRODUCT_FROM_WISHLIST",
  DELETE_PRODUCT_FROM_WISHLIST_SUCCESS: "DELETE_PRODUCT_FROM_WISHLIST_SUCCESS",
  DELETE_PRODUCT_FROM_WISHLIST_FAIL: "DELETE_PRODUCT_FROM_WISHLIST_FAIL",
};
// ======================================================

// ======================================================

export {
  COUPON_CODE_ACTIONS_TYPES,
  COUPONS_ACTIONS_TYPES,
  CART_ACTIONS_TYPES,
  WISHLIST_ACTIONS_TYPES,
};
