// ===============================================================
const PRODUCT_ACTIONS_TYPES = {
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",
  // =====================================
  CLEAR_PRODUCT: "CLEAR_PRODUCT",
  CLEAR_PRODUCT_SUCCESS: "CLEAR_PRODUCT_SUCCESS",
  CLEAR_PRODUCT_FAIL: "CLEAR_PRODUCT_FAIL",
  // =====================================
  POST_PRODUCT: "POST_PRODUCT",
  POST_PRODUCT_SUCCESS: "POST_PRODUCT_SUCCESS",
  POST_PRODUCT_FAIL: "POST_PRODUCT_FAIL",
  // =====================================
  PUT_PRODUCT: "PUT_PRODUCT",
  PUT_PRODUCT_SUCCESS: "PUT_PRODUCT_SUCCESS",
  PUT_PRODUCT_FAIL: "PUT_PRODUCT_FAIL",
  // =====================================
  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",
  // =====================================
  PUT_ACCEPT_PRODUCT: "PUT_ACCEPT_PRODUCT",
  PUT_ACCEPT_PRODUCT_SUCCESS: "PUT_ACCEPT_PRODUCT_SUCCESS",
  PUT_ACCEPT_PRODUCT_FAIL: "PUT_ACCEPT_PRODUCT_FAIL",
  // =====================================
  PUT_BLOCK_PRODUCT: "PUT_BLOCK_PRODUCT",
  PUT_BLOCK_PRODUCT_SUCCESS: "PUT_BLOCK_PRODUCT_SUCCESS",
  PUT_BLOCK_PRODUCT_FAIL: "PUT_BLOCK_PRODUCT_FAIL",
  // =====================================
  PUT_UNBLOCK_PRODUCT: "PUT_UNBLOCK_PRODUCT",
  PUT_UNBLOCK_PRODUCT_SUCCESS: "PUT_UNBLOCK_PRODUCT_SUCCESS",
  PUT_UNBLOCK_PRODUCT_FAIL: "PUT_UNBLOCK_PRODUCT_FAIL",
};
// ===============================================================

const PRODUCTS_ACTIONS_TYPES = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",
  // =====================================
  GET_SEARCHED_PRODUCTS: "GET_SEARCHED_PRODUCTS",
  GET_SEARCHED_PRODUCTS_SUCCESS: "GET_SEARCHED_PRODUCTS_SUCCESS",
  GET_SEARCHED_PRODUCTS_FAIL: "GET_SEARCHED_PRODUCTS_FAIL",
  // =====================================
  GET_ACCEPTED_SELLER_PRODUCTS: "GET_ACCEPTED_SELLER_PRODUCTS",
  GET_ACCEPTED_SELLER_PRODUCTS_SUCCESS: "GET_ACCEPTED_SELLER_PRODUCTS_SUCCESS",
  GET_ACCEPTED_SELLER_PRODUCTS_FAIL: "GET_ACCEPTED_SELLER_PRODUCTS_FAIL",
  // =====================================
  GET_SELLER_PRODUCTS: "GET_SELLER_PRODUCTS",
  GET_SELLER_PRODUCTS_SUCCESS: "GET_SELLER_PRODUCTS_SUCCESS",
  GET_SELLER_PRODUCTS_FAIL: "GET_SELLER_PRODUCTS_FAIL",
  // =====================================
  GET_FLASH_SALES_PRODUCTS: "GET_FLASH_SALES_PRODUCTS",
  GET_FLASH_SALES_PRODUCTS_SUCCESS: "GET_FLASH_SALES_PRODUCTS_SUCCESS",
  GET_FLASH_SALES_PRODUCTS_FAIL: "GET_FLASH_SALES_PRODUCTS_FAIL",
};
// ===============================================================

// ======================================================

// ======================================================
const COUPON_CODE_ACTIONS_TYPES = {
  POST_COUPON_CODE: "POST_COUPON_CODE",
  POST_COUPON_CODE_SUCCESS: "POST_COUPON_CODE_SUCCESS",
  POST_COUPON_CODE_FAIL: "POST_COUPON_CODE_FAIL",
};

const COUPONS_ACTIONS_TYPES = {
  GET_SELLER_COUPONS: "GET_SELLER_COUPONS",
  GET_SELLER_COUPONS_SUCCESS: "GET_SELLER_COUPONS_SUCCESS",
  GET_SELLER_COUPONS_FAIL: "GET_SELLER_COUPONS_FAIL",
};
// ======================================================
const CART_ACTIONS_TYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",
  // ===============================================
  GET_CART: "GET_CART",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAIL: "GET_CART_FAIL",
  // ===============================================
  DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
  DELETE_PRODUCT_FROM_CART_SUCCESS: "DELETE_PRODUCT_FROM_CART_SUCCESS",
  DELETE_PRODUCT_FROM_CART_FAIL: "DELETE_PRODUCT_FROM_CART_FAIL",
  // ===============================================
  PUT_CART: "PUT_CART",
  PUT_CART_SUCCESS: "PUT_CART_SUCCESS",
  PUT_CART_FAIL: "PUT_CART_FAIL",
};
// ======================================================

const WISHLIST_ACTIONS_TYPES = {
  ADD_PRODUCT_TO_WISHLIST: "ADD_PRODUCT_TO_WISHLIST",
  ADD_PRODUCT_TO_WISHLIST_SUCCESS: "ADD_PRODUCT_TO_WISHLIST_SUCCESS",
  ADD_PRODUCT_TO_WISHLIST_FAIL: "ADD_PRODUCT_TO_WISHLIST_FAIL",
  // ===============================================
  GET_WISHLIST: "GET_WISHLIST",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
  GET_WISHLIST_FAIL: "GET_WISHLIST_FAIL",
  // ===============================================
  DELETE_PRODUCT_FROM_WISHLIST: "DELETE_PRODUCT_FROM_WISHLIST",
  DELETE_PRODUCT_FROM_WISHLIST_SUCCESS: "DELETE_PRODUCT_FROM_WISHLIST_SUCCESS",
  DELETE_PRODUCT_FROM_WISHLIST_FAIL: "DELETE_PRODUCT_FROM_WISHLIST_FAIL",
};
// ======================================================

// ======================================================

export {
  PRODUCT_ACTIONS_TYPES,
  PRODUCTS_ACTIONS_TYPES,
  COUPON_CODE_ACTIONS_TYPES,
  COUPONS_ACTIONS_TYPES,
  CART_ACTIONS_TYPES,
  WISHLIST_ACTIONS_TYPES,
};
