export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const GET_SUB_CATEGORIES_SUCCESS = "GET_SUB_CATEGORIES_SUCCESS";
export const GET_SUB_CATEGORIES_FAIL = "GET_SUB_CATEGORIES_FAIL";

export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_FAIL = "GET_SUB_CATEGORY_FAIL";

export const POST_SUB_CATEGORY = "POST_SUB_CATEGORY";
export const POST_SUB_CATEGORY_SUCCESS = "POST_SUB_CATEGORY_SUCCESS";
export const POST_SUB_CATEGORY_FAIL = "POST_SUB_CATEGORY_FAIL";

export const PUT_SUB_CATEGORY = "PUT_SUB_CATEGORY";
export const PUT_SUB_CATEGORY_SUCCESS = "PUT_SUB_CATEGORY_SUCCESS";
export const PUT_SUB_CATEGORY_FAIL = "PUT_SUB_CATEGORY_FAIL";

export const DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAIL = "DELETE_SUB_CATEGORY_FAIL";
