export const GET_SOCIALS = "GET_SOCIALS";
export const GET_SOCIALS_SUCCESS = "GET_SOCIALS_SUCCESS";
export const GET_SOCIALS_FAIL = "GET_SOCIALS_FAIL";

export const GET_SOCIAL = "GET_SOCIAL";
export const GET_SOCIAL_SUCCESS = "GET_SOCIAL_SUCCESS";
export const GET_SOCIAL_FAIL = "GET_SOCIAL_FAIL";

export const POST_ADD_SOCIAL = "POST_ADD_SOCIAL";
export const POST_ADD_SOCIAL_SUCCESS = "POST_ADD_SOCIAL_SUCCESS";
export const POST_ADD_SOCIAL_FAIL = "POST_ADD_SOCIAL_FAIL";

export const DELETE_SOCIAL = "DELETE_SOCIAL";
export const DELETE_SOCIAL_SUCCESS = "DELETE_SOCIAL_SUCCESS";
export const DELETE_SOCIAL_FAIL = "DELETE_SOCIAL_FAIL";

export const PUT_SOCIAL = "PUT_SOCIAL";
export const PUT_SOCIAL_SUCCESS = "PUT_SOCIAL_SUCCESS";
export const PUT_SOCIAL_FAIL = "PUT_SOCIAL_FAIL";
