export const GET_PAGE_SECTIONS = "GET_PAGE_SECTIONS";
export const GET_PAGE_SECTIONS_SUCCESS = "GET_PAGE_SECTIONS_SUCCESS";
export const GET_PAGE_SECTIONS_FAIL = "GET_PAGE_SECTIONS_FAIL";

export const GET_PAGE_SECTION = "GET_PAGE_SECTION";
export const GET_PAGE_SECTION_SUCCESS = "GET_PAGE_SECTION_SUCCESS";
export const GET_PAGE_SECTION_FAIL = "GET_PAGE_SECTION_FAIL";

export const POST_PAGE_SECTION = "POST_PAGE_SECTION";
export const POST_PAGE_SECTION_SUCCESS = "POST_PAGE_SECTION_SUCCESS";
export const POST_PAGE_SECTION_FAIL = "POST_PAGE_SECTION_FAIL";

export const PUT_PAGE_SECTION = "PUT_PAGE_SECTION";
export const PUT_PAGE_SECTION_SUCCESS = "PUT_PAGE_SECTION_SUCCESS";
export const PUT_PAGE_SECTION_FAIL = "PUT_PAGE_SECTION_FAIL";

export const DELETE_PAGE_SECTION = "DELETE_PAGE_SECTION";
export const DELETE_PAGE_SECTION_SUCCESS = "DELETE_PAGE_SECTION_SUCCESS";
export const DELETE_PAGE_SECTION_FAIL = "DELETE_PAGE_SECTION_FAIL";
