export const GET_SETTINGS = "GET_SETTINGS";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAIL = "GET_SETTINGS_FAIL";

export const PUT_SETTINGS = "PUT_SETTINGS";
export const PUT_SETTINGS_SUCCESS = "PUT_SETTINGS_SUCCESS";
export const PUT_SETTINGS_FAIL = "PUT_SETTINGS_FAIL";
